### ISSUE TITLE
Docker image can't execute debricked:scan

### ISSUE THREAD

**Issue by JakobHagg2** [debricked/debricked-cli#66]
All our checks fails with response:
`/usr/local/bin/docker-php-entrypoint: exec: line 9: debricked:scan: not found`

Running docker with command:
`docker run -i --rm -v C:\Source\DevOpsTools:/data debricked/debricked-cli:latest debricked:check-scan <user> <pass> <repo> <commit> null cli`
Digest : sha256:0884ad477cd3a4ab4f4875bb178801f2eb96d9aedee42ddf14df46bb4958c205

Last known good image is (we will run on this image as a workaround):
sha256:c5e11ba3ddff2ab252fba0cc7b92f6966700aa61044f334d244776c37909f720

Let me know if I can help out

**Comment by zozs** [comment]
Hi @JakobHagg2!

Thanks for bringing this to our attention.

There was a bug due to a recent refactoring of our Dockerfile. We've now fixed it and published a new version of the image. The `latest` tag should now work, if you pull the newest version.

**Comment by JakobHagg2** [comment]
Perfect,
confirmed working with:
 sha256:f1f392e579e48e3165a556947e32fda84bddbbcccf54956697326550315011dd
