### ISSUE TITLE
Scan link is broken

### ISSUE THREAD

**Issue by viktigpetterr** [debricked/debricked-cli#68]
After a finished scan it is possible to look more closely on the results over at Debricked, the link however is broken.
![image](https://user-images.githubusercontent.com/36230100/152962567-9a5e4cd3-3da4-409b-994c-76cd28156e09.png)
## Tasks
- [x] Make sure the proper link is there

**Comment by viktigpetterr** [comment]
Since the last push to production the issue has been resolved.

**Comment by sweoggy** [comment]
Excellent, thanks for fixing this issue.

To clarify, this was a bug in Debricked's API which has since been fixed
